### ISSUE TITLE
Time complexity

### ISSUE THREAD

**Issue by fruzsinaagocs** [karlotness/adrt#4]
Hi,

I checked the time complexity of ADRT for NxN images similar to those in the quickstart example:

``` python
import numpy as np
import time
import adrt

nmin = 2
nmax = 14
num = nmax - nmin + 1
ns = np.logspace(nmin, nmax, num = num, base = 2)
times = np.zeros(num)
timen = 10000
for i, n in enumerate(ns):
    nint = int(n)
    xs = np.linspace(-1, 1, nint)
    x, y = np.meshgrid(xs, xs)
    img = 0.5 * ((np.abs(x - 0.25) + np.abs(y)) < 0.7).astype(np.float32)
    img[:, np.random.randint(0, nint-1)] = 1
    img[np.random.randint(0, nint-1), :] = 1
    start = time.time()
    if n > 100:
        timen = 1000
    if n > 1000:
        timen = 10
    if n > 10000:
        timen = 1
    for j in range(timen):
       result = adrt.adrt(img)
    end = time.time()
    times[i] = (end - start)/timen
```

This gave me:
[scaling.pdf](https://github.com/karlotness/adrt/files/10962322/scaling.pdf)

So the claim that the algorithm is O(N^2 log N) is clearly true (in the limit of large N), but I was wondering if you also noted that between N = 2^7 and N = 2^10 (which may be typical image sizes) it scales more like N^3? 

Thanks!

**Comment by karlotness** [comment]
Thanks for running those tests; running your timing code I do see the same thing.

I suspect the bend in the curve is largely driven by cache effects. The time for the adrt to run is bounded mainly by memory bandwidth so the time required to pass through both of the internal buffers is what should mainly drive the scaling. It really should be scaling as $O(n^2 \log_2(n))$ since that's the number of memory accesses, but with different memory access costs as the buffers grow.

In that plot, I think what's mostly happening is that as the size of the image grows larger, eventually it becomes too large for each layer in your processor's cache, finally requiring access to main memory. That's the point where the scaling should become really consistent.

To try to look at that, I reran some measurements similar to the timings you ran, but adjusting the batch dimension so that the buffers are closer to the same size in each trial. So we start with a very large batch for the 2x2 images, then divide by a factor of 4 each time the image dimension doubles.

<details>
  <summary>Test Code</summary>

```python
import numpy as np
import time
import statistics
import adrt
import math
from tqdm.auto import tqdm

TRIALS = 3
ns = [2**i for i in range(1, 15)]
batch_sizes = [(max(ns) // n)**2 for n in ns]
times = []
buf_sizes = []

rng = np.random.default_rng()

for n, batch_size in tqdm(zip(ns, batch_sizes), total=len(ns)):
    # Init image
    img = rng.normal(size=(batch_size, n, n))
    # Run trials
    iter_times = []
    for i in range(TRIALS):
        start = time.perf_counter()
        res = adrt.adrt(img)
        end = time.perf_counter()
        buf_size = res[0].nbytes
        res = None
        iter_times.append((end - start) / batch_size)
    buf_sizes.append(buf_size)
    times.append(statistics.mean(iter_times))
```

</details>

With that I get a more consistent trend, without the odd bend in the timing curve early on (plotted below with a trend line).

![fig](https://user-images.githubusercontent.com/8847665/224882839-f3e6cd41-1576-459d-bf61-8591112640c2.png)

Does that seem to make sense?

Thanks again for taking a look

**Comment by fruzsinaagocs** [comment]
That makes perfect sense, thank you for looking into it and explaining!

**Comment by karlotness** [comment]
Glad to hear it. Thanks again for taking a look
